# Generated by Django 5.0.6 on 2025-07-27 07:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProdMast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_code', models.CharField(help_text='Unique product code', max_length=20, unique=True)),
                ('prod_name', models.CharField(help_text='Product name', max_length=255)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('food', 'Food'), ('books', 'Books'), ('other', 'Other')], default='other', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('min_stock_level', models.IntegerField(default=0, help_text='Minimum stock level alert', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Master',
                'verbose_name_plural': 'Product Masters',
                'db_table': 'prodmast',
            },
        ),
        migrations.CreateModel(
            name='StckMain',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('trans_date', models.DateTimeField(help_text='Transaction date and time')),
                ('trans_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJ', 'Adjustment')], max_length=3)),
                ('reference_no', models.CharField(blank=True, help_text='Reference number (PO, Invoice, etc.)', max_length=50)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks')),
                ('created_by', models.CharField(default='system', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stock Transaction',
                'verbose_name_plural': 'Stock Transactions',
                'db_table': 'stckmain',
                'ordering': ['-trans_date'],
            },
        ),
        migrations.CreateModel(
            name='StckDetail',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(help_text='Quantity moved', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Cost per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.prodmast')),
                ('trans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='inventory.stckmain')),
            ],
            options={
                'verbose_name': 'Stock Detail',
                'verbose_name_plural': 'Stock Details',
                'db_table': 'stckdetail',
                'unique_together': {('trans', 'product')},
            },
        ),
    ]
